typography_spectrum: 0.5817333795130253
color:
  brandStrength: 0.7234133915044367
  lightness: 0.13291927729733288
  saturation: 0.4590976978652179
  rhythmicContrast: 0.45065680239349604
  brandColors:
    - '#FFFFFF'
    - '#94D4D1'
    - '#5C7385'
    - '#0086A1'
    - '#5BB3C4'
layout_spectrum: 0.7353152604773641
author:
  name: Hugh Mc Afee
  email: martinmcafee@hrdservices.co.uk
  url: 'http://hrdservices.co.uk/'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/41857a07-d4d4-4089-b818-fb417d15dac2.gif
name: HRD Services
title: Bringing out the best in people
description: ''
